/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=gateway/wrangler.example.jsonc --include-runtime=false --strict-vars=false gateway/worker-configuration.d.ts` (hash: e13cef501c9f80c2b0a0b21307a0715b)
interface __BaseEnv_Env {
	PUBLISH_HOST: string;
	CLOUDFLARE_ZONE_ID: string;
	INDEX_TITLE: string;
	WORKER_PREFIX: string;
	CLOUDFLARE_API_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLISH_HOST" | "CLOUDFLARE_ZONE_ID" | "INDEX_TITLE" | "WORKER_PREFIX" | "CLOUDFLARE_API_TOKEN">> {}
}
